# 应用服务 WEB 访问端口
server:
  port: 9100



codesandbox:
  global-code-path: "codeStorage"

auth:
  request-header-text: "X-FORWARDED-FOR-CODE"
  request-header-value: "JUDGE-CLIENT"

thread-pool:
  instances:
    timeout-watch-dog:
      corePoolSize: 2
      maxPoolSize: 4
      queueCapacity: 30
      keepAliveSeconds: 120
      timeUnit: SECONDS